### PR TITLE
Add solid-filemanager to solid-apps list

### PR DESCRIPTION
**Pull request by Otto-AA**
I've added the solid-filemanager to the solid-apps list. It's a project I've been working on the for the last two weeks, which allows navigating and managing the solid pod.

### CODE REVIEW

**Comment by Otto-AA** [comment]
Is there anything missing from my side to get this PR merged?

**Comment by megoth** [comment]
LGTM ^_^

**Comment by Otto-AA** [comment]
I don't want to stress you, but... lets get this merged? o.O

**Comment by angelo-v** [comment]
Since I included info from the wiki, this is also included in https://github.com/solid/solid-apps/pull/34

**Comment by Otto-AA** [comment]
Added in https://github.com/solid/solid-apps/pull/34

**Pull request closed without merging**
