### PR TITLE
Add two personal data apps

### PR DESCRIPTION
**Pull request by dconorozzo**
File Extractor for PODs and Solid POD Form Integration

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Thanks!

**Comment by bourgeoa** [comment]
These 2 apps are a professional service.
I don't think they should be listed here or on a special category

**Comment by melvincarvalho** [comment]
@bourgeoa good feedback!

To date we've listed all apps that want to be listed.  Mainly because : 

- our app universe is quite small
- inclusion has been prioritized over curation
- we have relatively few maintainers for this repo

But as the apps dir, and solid grows we can apply curation.  The key consideration is that we are neutral and fair in that regard.

It's possibly a good point to start a curation process.  Some of my own apps are not working with the latest node solid server.  You can argue that's possibly more a weakness of node solid server, than my apps :P  But I'll probably delist some of my own (sadly), in the name of progress.  

That will depend on simply how much time volunteers have to throw at it.  Solid should be open to all sorts of services.  We can categorize them better.  

Regarding this specific app, I just checked it out and log in worked, there also seemed to be an instuctional video, which is pretty nice, though I didnt watch all the way through!  Perhaps I should have asked what it does.  I get the login and "Get File List", but what after that?

**Comment by bourgeoa** [comment]
These 2 apps are part of a paid service with a trial period.

As for your apps I personally think they should be kept as an example on
may be a special category. I would love to make then work. Is it only a
login pb or more ?

Le mer. 20 févr. 2019 à 11:38, Melvin Carvalho <notifications@github.com> a
écrit :

**Comment by dconorozzo** [comment]
The File Extractor is actually MIT license. If you have a file in your POD with data of type hexBinary, it can extract and send that file to you. You just login (this uses the exact same code for authentication that the make a solid app on your lunchbreak uses) and give it the URL to your file.

The other app is part of our paid service. At this time, we are hoping people will start to demand copies of forms (and the data) they fill out. The users of that product may be our customers who want to store all of their collected data in a POD, but the video and the push is more about end users (not our customers) getting a copy of their data and form when they fill it out (which, is not something we charge them for).

**Comment by megoth** [comment]
I don't think [Solid POD Form Integration](https://www.formrouter.com/solid-project-pod-pdf-form-integration/online_forms_solid_pod.htm) should be listed under *Personal Data Apps*, and it should be labeled as part of a paid service (or requires a trial at least).

I think I'll create a PR with a suggestion for how this can be changed, and maybe set a precedence for how we treat paid services in the future.

I have some meetings before I have time though, so any suggestions on these points are very much appreciated ^_^

**Comment by bourgeoa** [comment]
Personally, but I am not an expert I think GitHub is not the place for paid
services with may be ?? exception when the source is open-source.

I understand that promoting solid is an objective.

Information could be allowed if it's agreed on chat or forum ? Or Inrupt
could manage a web list ?

Le mer. 20 févr. 2019 à 14:02, Arne Hassel <notifications@github.com> a
écrit :

**Pull request merged**
