### PR TITLE
An attempt at making the presentation of paid services clearer

### PR DESCRIPTION
**Pull request by megoth**
Hopefully this can set a good precedence for this.

Relates to
- https://github.com/solid/solid-apps/pull/26
- https://github.com/solid/solid-apps/issues/27

### CODE REVIEW

**Comment by melvincarvalho** [comment]
@megoth thanks for helping out here, much appreciated

LGTM!

I'll leave this open a bit in case anyone else wants to weigh in

**Comment by melvincarvalho** [comment]
A little side note, which I think is on topic.  Is it time we started to make a list of apps using RDF too?

A simple first step would be to put things in more of a tabular form.  Then we could think about a script that converts markdown to turtle.

**Comment by megoth** [comment]
I would love having this list represented as RDF ^_^ But important that the process of adding apps remain simple for now, I think, so think maybe it's still a bit to early?

Maybe create a separate issue for it, where we can spec out the details of how this _could_ work?

**Comment by megoth** [comment]
> I'll leave this open a bit in case anyone else wants to weigh in

Nobody has chimed in it seems, maybe we should merge this?

**Comment by melvincarvalho** [comment]
Please, looks good!

**Comment by megoth** [comment]
I will wait to merge this until we have resolved https://github.com/solid/community/pull/70.

**Comment by melvincarvalho** [comment]
> I will wait to merge this until we have resolved solid/community#70

Seems orthogonal.  But no issue if you'd like to wait.

If you dont get round it it, I'll merge this in due course.  Thanks again for helping out, it's much appreciated!

**Pull request merged**
