### PR TITLE
gh-pages branch needs these changes

### PR DESCRIPTION
**Pull request by TallTed**
`gh-pages` branch is the one that's auto-displayed ... so PRs should be made against `gh-pages`, not against `master`

### CODE REVIEW

**Review by megoth — APPROVED** [review]
LGTM

**Comment by melvincarvalho** [comment]
Thanks alot!  gh-pages is the default now.

Perhaps we should delete master to avoid confusion?  

Any objections?

**Comment by TallTed** [comment]
I cannot resolve these merge conflicts; they're not even displayed to me -- only announced.

This might also be another case of "PRs must wait 3 days (or 2 weeks)" makes little or no sense.

**Comment by TallTed** [comment]
@megoth @melvincarvalho @Mitzi-Laszlo @timbl -- 

I am increasingly concerned that the mandated two week (or three day, or whatever the latest is) period for all (code or non-code or ) PRs is preventing even uncontroversial PRs from being merged at all.

The collection of changes in this PR were previously applied to the even-then-deprecated `master` branch, and should have been applied to the `gh-pages` branch -- which is all this PR does! -- but this PR still lingers, nearly 4 weeks later.

Because of that long delay, someone with write access to one of the branches (I'm not sure which is affected; I *think* it's the `master`) needs to resolve the branch conflicts which now exist (and which will no doubt continue to increase over time, as there were none when the PR was originally submitted) such that this PR *can* be merged.

**Comment by melvincarvalho** [comment]
@TallTed as per my comment above, I think we should delete master, and have only gh-pages ...

**Comment by TallTed** [comment]
@melvincarvalho said --
> @TallTed as per my comment above, I think we should delete master, and have only gh-pages ...

Sure, but that has no impact on, and is actually supported by, this PR (which brings changes previously [and arguably erroneously] made to `master` into `gh-pages`) ... and ignores the part where this probably would have been merged near-immediately upon creation, but for the required waiting period.

**Comment by TallTed** [comment]
@melvincarvalho @jeff-zucker @wrmack @nicola @deiu @pheyvaer @nleanba @dmitrizagidulin @rhiaro @csarven @crmepham @bourgeoa
(in other words, everyone who's shown as having previously committed to the `master` branch, and might be able to do so again, to resolve the current conflicts of this PR)

I cannot _see_ the "conflicts that must be resolved", because I don't have write access to the `master` branch which is the source for this PR for `gh-pages`.  I'm happy to consult with whomever is willing and able to resolve the conflicts, so that these changes can be applied to `gh-pages`, so that `master` can be dropped/closed/whatever, to remove the [ongoing conflict/confusion](https://github.com/solid/solid-apps/pull/31).

**Comment by wrmack** [comment]
One of the PRs to master is mine.  Would it help to close this PR and I do it again against gh-pages? (I am a bit new with this).

**Comment by TallTed** [comment]
@wrmack --

> One of the PRs to master is mine. Would it help to close this PR and I do it again against `gh-pages`? (I am a bit new with this).

That should not be necessary ... and I can't see any reason why your new PR (and the other(s) which would then also be necessarily redone against `gh-pages`) would be merged sooner than this.  Git is built to handle this sort of thing -- it just needs a couple minutes of attention from the right human.

**Pull request merged**
