### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**

### CODE REVIEW

**Comment by megoth** [comment]
Would've been nice with a description of the application.

**Comment by michielbdejong** [comment]
It's unclear to me how https://referendum.signons.fr can be used in connection with a WebId and/or a Solid pod.

**Comment by TallTed** [comment]
@michielbdejong @megoth 

Seems those comments ought to feed (a) new issue(s), as they're unlikely to get much attention on a (long-ago-)merged PR.

**Comment by michielbdejong** [comment]
Thanks @TallTed, created https://github.com/solid/solid-apps/issues/60 about this.

**Pull request merged**
